---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world
  labels:
    name: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
      - name: hello-world
        image: gcr.io/gcp-weave-cicd/go-hello-world:master-cc97017
        ports:
        - containerPort: 8080
